
import React from 'https://esm.sh/react@^19.2.3';

const TermsPage: React.FC = () => {
  return (
    <div className="pt-40 pb-24 px-4 max-w-4xl mx-auto animate-in fade-in duration-700">
      <div className="bg-white p-12 md:p-20 rounded-[40px] border border-slate-100 shadow-2xl">
        <h1 className="text-5xl font-bold text-teal-950 tracking-tight serif-heading mb-12">Terms & Disclaimer</h1>
        
        <div className="bg-red-50 border-l-4 border-red-500 p-10 rounded-3xl mb-12">
          <h2 className="text-[#D32F2F] font-bold text-xl mb-4 flex items-center gap-3">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
            MEDICAL DISCLAIMER
          </h2>
          <p className="text-red-900 text-lg font-bold leading-relaxed serif-heading italic">
            "NaijaHealth is NOT a medical facility. We do not employ doctors, nor do we provide medical advice, diagnosis, or treatment. All content, including reviews and AI-generated insights, is for informational purposes only."
          </p>
          <p className="mt-6 text-red-800 font-medium">If you are experiencing a life-threatening emergency, stop using this app and dial local emergency services or head to the nearest verified emergency room immediately.</p>
        </div>

        <div className="prose prose-slate prose-lg max-w-none text-slate-600 leading-relaxed space-y-10">
          <section>
            <h2 className="text-2xl font-bold text-teal-950 serif-heading mb-4">1. Use of Platform</h2>
            <p>By accessing NaijaHealth, you agree to use the data provided "as is". While we strive for accuracy, review data is generated by users and may not reflect real-time hospital changes.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-teal-950 serif-heading mb-4">2. Prohibited Conduct</h2>
            <p>Users are strictly prohibited from posting fraudulent reviews, spam, or defamatory content targeting specific medical professionals. We reserve the right to ban accounts that violate our "Patient Integrity" standard.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-teal-950 serif-heading mb-4">3. Limitation of Liability</h2>
            <p>NaijaHealth Reviews shall not be liable for any medical outcomes, financial losses, or decisions made based on the information provided on this platform.</p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
